name: Publish to NuGet

on:
  push:
    branches:
      - master
    paths:
      - './CrudGenerator.Cli/CrudGenerator.Cli.csproj'
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore CrudGenerator.Cli/CrudGenerator.Cli.csproj  

    - name: Build the project
      run: dotnet build CrudGenerator.Cli/CrudGenerator.Cli.csproj --configuration Release  

    - name: Pack the project
      run: dotnet pack CrudGenerator.Cli/CrudGenerator.Cli.csproj --configuration Release --output ./output  

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./output/CrudGenerator.Cli*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
